package com.example.nawibackend.common.models.enums;

public enum TestType {
    WEIGHING_PERFORMANCE, TEMPERATURE_EFFECT, ECCENTRICITY_WEIGHTS, ECCENTRICITY_ROLLING,
    DISCRIMINATION_DIGITAL, DISCRIMINATION_ANALOG, SENSITIVITY, REPEATABILITY,
    ZERO_RETURN, CREEP, STABILITY_OF_EQUILIBRIUM, TILTING, TARE, WARM_UP_TIME,
    VOLTAGE_VARIATIONS, ELECTRICAL_DISTURBANCE, DAMP_HEAT, SPAN_STABILITY, ENDURANCE
}
